### ISSUE TITLE
Bug: pasting in quick succession causes error

### ISSUE THREAD

**Issue by chrisgrieser** [gbprod/yanky.nvim#100]
to reproduce:
- yank a line
- repeatedly press `p` in quick succession

result:
~every third paste or so create this message:
![CleanShot 2023-03-22 at 16 47 59](https://user-images.githubusercontent.com/73286100/226961858-1b921c78-a60b-4139-83f3-4a146779d019.png)

**Comment by gbprod** [comment]
Thanks for reporting this issue.

Can you share your yanky setup ? 
Do you use sqlite as storage ?

**Comment by chrisgrieser** [comment]
No, I have been using yanky without sqlite storage.

Also, I am afraid I cannot reproduced the issue anymore. However, considering it was a `vim.schedule`-related, when the issue occurred, I was running nvim on an older, much slower machine 🤔

**Comment by gbprod** [comment]
Ok, feel free to re-open if it comes back !
