### ISSUE TITLE
Getting an error when `virtualedit = 'all'`

### ISSUE THREAD

**Issue by farzadmf** [gbprod/yanky.nvim#101]
Hi, I have `virtualedit = 'all'` in my config, and if I try to yank a block of text while my cursor is positioned in a "virtual" column, I get the following error:

```
Error  08:01:25 PM msg_show.lua_error Error detected while processing TextYankPost Autocommands for "*":
08:01:25 PM msg_show Error executing lua callback: ...ar/neovim/0.9.0/share/nvim/runtime/lua/vim/highlight.lua:42: Invalid 'end_col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_extmark'
	...ar/neovim/0.9.0/share/nvim/runtime/lua/vim/highlight.lua:42: in function 'range'
	...ar/neovim/0.9.0/share/nvim/runtime/lua/vim/highlight.lua:113: in function 'on_yank'
	...y_lazy/data/nvim/lazy/yanky.nvim/lua/yanky/highlight.lua:17: in function <...y_lazy/data/nvim/lazy/yanky.nvim/lua/yanky/highlight.lua:16>
```

Please let me know if there's any other information I can provide

**Comment by gbprod** [comment]
Interesting, I try to fix it soon !

**Comment by farzadmf** [comment]
Oh no, sad 🙁. I was looking forward to the fix @gbprod 

Isn't it at least possible to handle the error more gracefully?

**Comment by gbprod** [comment]
Here it is : https://github.com/gbprod/yanky.nvim/pull/107
Do you want to try before I merge ?

**Comment by farzadmf** [comment]
Sure thing, let me try

**Comment by farzadmf** [comment]
So, tried it, and the error doesn't show up, but it also doesn't do the post-yank highlighting. I guess it's not possible to do that, is it?

**Comment by gbprod** [comment]
AFAIK, It doesn't seems to be possible :/
I think I'll merge this as it and I'll try to improve it later.
Thanks !

**Comment by farzadmf** [comment]
Thank you for the fix, let me know if I can help with anything
