### ISSUE TITLE
stack traceback: [C]: in function 'getreg'

### ISSUE THREAD

**Issue by Caberlotto** [gbprod/yanky.nvim#102]
![2023-04-14_17-33](https://user-images.githubusercontent.com/98235781/232089189-a8178955-90aa-426e-92fd-a6b81a9d11c5.png)

**Comment by gbprod** [comment]
Hi, can you check this issue : https://github.com/gbprod/yanky.nvim/issues/91
It seems that it could be the same.

Otherwise, can you share your config ?
