### ISSUE TITLE
About telescope mappings

### ISSUE THREAD

**Issue by jqhr** [gbprod/yanky.nvim#103]
nvim: 0.9.0
telescope: 0.1.1
yank config:
![图片](https://user-images.githubusercontent.com/23305067/232181415-9c002138-77d8-4dd7-bc1e-e026b1d32515.png)
question:
 I don't need default keymap in telescope, so I set picker.telescope.mappings.i/n to {}, but it doesnot work. 
![图片](https://user-images.githubusercontent.com/23305067/232181628-b671bd7f-feec-4f83-be40-5996ea69e90c.png)

How to config it?

**Comment by gbprod** [comment]
Hey, I think it's since I merge mappings with `vim.tbl_deep_extend` instead of replacing them (see https://github.com/gbprod/yanky.nvim/commit/c4c794afd762a00ca543972e5b9e34ce9aa14a87)
That's make impossible to remove a mapping, I think that I should revert.

**Comment by gbprod** [comment]
Hey!

Sorry for the late feedback.

I've made something that should fix your ptoblem here : #106 
Can you confirm ?

Thanks

**Comment by xeluxee** [comment]
I think users should be able to disable default telescope keymaps.
Currently yanky maps `<C-k>` to `P`, but it overrides my telescope config that maps `<C-k>` to `move_selection_previous`

https://github.com/gbprod/yanky.nvim/blob/412583be00797acbda63885bbf0c098485688156/lua/yanky/telescope/mapping.lua#L60

@gbprod would you agree adding a setup option like `picker.telescope.use_default_mappings`? When it's false mappings should be replaced and not extended.

**Comment by gbprod** [comment]
Good idea, I tryto implements this soon

**Comment by gbprod** [comment]
Done :)
