### ISSUE TITLE
causes cursor blink

### ISSUE THREAD

**Issue by jam1015** [gbprod/yanky.nvim#104]
when I install yanky using lazy.nvim with no other configuration besides running yanky's  empty 'setup' function, both on my mac and using Xorg+i3 on Arch, clicking another window and then clicking the terminal window where neovim is running is causes brief, quick, cursor blinking.

**Comment by jam1015** [comment]
just checked that this happens both on neovim 0.8.2 and 0.9.0

**Comment by jacek-kurlit** [comment]
Im my case this plugin was causing window flickering making nvim unusable.
I am using fedora 37 and nvim 0.9

**Comment by calzonegnome** [comment]
+1 on @jacek-kurlit 's situation. Same happens w/ me. Also Fedora 37 and nvim 0.9.

**Comment by gbprod** [comment]
@jacek-kurlit @calzonegnome It could be an issue with `xclip`, can you try to follow this : https://github.com/gbprod/yanky.nvim/issues/37#issuecomment-1193671730 and tell me if it fix the issue ?

**Comment by gbprod** [comment]
@jam1015 I try to reproduce the issue and I come back to you.

**Comment by mokafolio** [comment]
Having the same issue on arch/kitty/with neovim nightly where sometimes when I start nvim, it flickers and becomes totally unusable, while other times it only flickers for a moment.

**Comment by gbprod** [comment]
I think it should have been fixed by #117 , can you confirm ?

**Comment by jacek-kurlit** [comment]
Yes, it works now!
Thank you

czw., 28 wrz 2023, 07:51 użytkownik gbprod ***@***.***>
napisał:

**Comment by jam1015** [comment]
Hi! I'm sorry to be a nuisance but the problem is persisting on my end.

**Comment by folke** [comment]
@jam1015 some blinking is to be expected (and not possible to fix).

What I did fix however, was en endless loop making the desktop environment pretty much unresponsive.
