### ISSUE TITLE
osc52 support

### ISSUE THREAD

**Issue by davidosomething** [gbprod/yanky.nvim#113]
when in an ssh session, you typically don't have access to system/x11 clipboards
but you can use built-in terminal emulator codes to copy things into your system clipboard via osc52

a plugin that tells nvim to use osc52:
https://github.com/ojroques/nvim-osc52

in this case, i would like to be able to first yank into yanky, and then output the osc52 code (chaining on to nvim-osc52) to push the same yanked text into my system clipboard

**Comment by gbprod** [comment]
Since [this commit](https://github.com/neovim/neovim/commit/748bc4d22d35b40f0795015e5d93113b526adf22) you can use osc52 as clipboard directly in Neovim nightly.
Can you try with this config and send me feedback: 

```lua
    vim.g.clipboard = {
      name = 'OSC 52',
      copy = {
        ['+'] = require('vim.clipboard.osc52').copy,
        ['*'] = require('vim.clipboard.osc52').copy,
      },
      paste = {
        ['+'] = require('vim.clipboard.osc52').paste,
        ['*'] = require('vim.clipboard.osc52').paste,
      },
    }
```

If it works, we could add a section in the readme :)
