### ISSUE TITLE
Requesting Enhancement for `telescope extension` to Replace Selected Text with Visual Select.

### ISSUE THREAD

**Issue by nsoufian** [gbprod/yanky.nvim#116]
## Issue Description

Firstly, I would like to express my gratitude for the excellent `yanky.nvim` plugin, which has significantly enhanced my workflow. It has been a valuable addition to my workflow.

I have been using the `require('telescope').extensions.yank_history.yank_history()` function in my Vim mapping (`vim.keymap.set({'n', 'v'}, '<C-p>', require('telescope').extensions.yank_history.yank_history)`), and it has been working well. However, I have encountered a slight issue related to its behavior with visual selection.

Currently, when I use `require('telescope').extensions.yank_history.yank_history()` with visual selection, it pastes the content without replacing the selected text. I would like to request an enhancement that enables the replacement of selected text with the pasted content.

Could you please guide me on whether I am using the function correctly or if there is another approach I should follow? It would be immensely helpful to know if I am missing something or if this behavior can be improved.

Thank you for your time and support.

**Comment by gbprod** [comment]
Hey, I remember I had some problems with that. I'll make some research and I keep you in touch.

**Comment by nsoufian** [comment]
Any update on this.

**Comment by gbprod** [comment]
Should be fixed, let me know if it's ok for your :)

**Comment by nsoufian** [comment]
Yes it's working as expected , thanks for the fix.
