### ISSUE TITLE
 Bug while trying to use yanker.nvim remap

### ISSUE THREAD

**Issue by PhantomPixelist** [gbprod/yanky.nvim#119]
**Description:**

I am trying to import the yanker.nvim plugin. However, I am getting a bug when I try to run the keymap `<leader>yh`.

The plugin is imported as follows:
```
{ -- Imrpoved Yank
"arsham/yanker.nvim",
dependencies = { "arsham/arshlib.nvim", "junegunn/fzf.vim" },
-- config = true,
-- or to provide configurations
config = { history = "<leader>yh" },
},
```

When I run the keymap, I get the following error:
```
E5108: Error executing lua: Vim:E117: Unknown function: fzf#wrap
stack traceback:
        [C]: in function 'fzf#wrap'
        ...p/.local/share/nvim/lazy/yanker.nvim/lua/yanker/init.lua:68: in function <...p/.local/share/nvim/lazy/yanker.nvim/lua/yanker/init.lua:32>
Error: Couldn't load plugin: yanker.nvim
```

**Additional Information:**

* My operating system is Ubuntu .
* I am using NVIM v0.9.1.
* I am using Lazy as a plugin manager
* the dependencies plugins seems to be installed correctly.  I run `:Lazy` and they show up.

**Thank you for your help!**

**Comment by gbprod** [comment]
I think you should post this issue in arsham/yanker.nvim repository 😉

**Comment by PhantomPixelist** [comment]
Sorry about that! Thanks for responding so quickly. 
I am closing the issue.
