### ISSUE TITLE
[Discussion] Shouldn't YankyCycleForward be swapped with YankyCycleBackward? And probably renamed?

### ISSUE THREAD

**Issue by RayJameson** [gbprod/yanky.nvim#122]
Hear me out, I know that I can map and name those in my config as I like, but I believe this makes sense for everyone.

I think of yanky history as a stack and when I yank something, in my perception every new entry in yanky stack is the next entry and the older entry is the previous.
I caught myself pressing `<M-p>` multiple times, expecting it to go back in yank history, but in this plugin, it's kind of flipped.

So imagine your yanky stack looks like this (the top is oldest, the bottom is latest):

- Roses are red
- Violets are blue
- Sugar is sweet
- And so are you

Now I want to paste them in the same order, in my head I know that "Roses are red" is the oldest line, therefore I would press `<M-p>` because it's usually how things are done, so it's just muscle memory, for example:

- when you press `<C-o>` you go back in the jump list (for me it's the same idea as `<C-p>` because you can also think of jumplist as a stack) `<C-i>` to go forward
- when you search you press `p` for the previous occurrence, `n`  for next
- in TMUX you press `<prefix>p` for previous window, `<prefix>n` for next window
- default vim's completion - omnicomp also works this way - `<C-p>` for the previous entry, `<C-n>` for next.

So shouldn't it be something like `YankyPreviousEntry` and `YankyNextEntry` or at least shouldn't they swap what they do and be going back from a stack perspective and not from a perspective of depth like next is a deeper level?

**Comment by gbprod** [comment]
Hey!
That's interesting and I think you're right.
As I don't want to break backward compatibility, I think we should add command with better names (like `YankyPreviousEntry` and `YankyNextEntry`).

Thanks for your feedback

**Comment by gbprod** [comment]
Thanks for your feedbacks, I'll try to update this soon ;)

**Comment by gbprod** [comment]
I've made something here: https://github.com/gbprod/yanky.nvim/pull/163
I think it should be better, can you confirm @TamaMcGlinn @RayJameson ?

**Comment by RayJameson** [comment]
Yep, it works fine
