### ISSUE TITLE
 Feature Request: Mapping Yank Operation to Specific Register

### ISSUE THREAD

**Issue by kevintraver** [gbprod/yanky.nvim#125]
I'm interested in a feature that sets a key mapping for yanking text directly into a chosen register.

Is there a method to provide a specific register as an option to `<Plug>(YankyYank)` or `yanky.yank`?

This would streamline the process of yanking text into a specific register, like the system register. 

If this already exists, any guidance would be appreciated.

**Comment by gbprod** [comment]
Hey!

You can just use : `vim.keymap.set({"n","x"}, "y", '"5<Plug>(YankyYank)')` where `"5` is the register you want to yank to.

**Comment by kevintraver** [comment]
Thanks! This works great:

```vim.keymap.set({ "n", "x" }, "Y", '"+<Plug>(YankyYank)')```

One other question:

How would I set `YY` to do the same thing, but with an operator after.

I want to call `YankyYank` with the * clipboard, and then execute `y` (yank line) after.

Essentially I want to be able to have `YY` yank the current line to the global clipboard register.

**Comment by kevintraver** [comment]
Also doing this:

```vim.keymap.set({ "n", "x" }, "Y", '"+<Plug>(YankyYank)')```

sets both the unnamed register and the system clipboard. I was wondering if there was a way to only have it set the system register?

**Comment by kevintraver** [comment]
Ah yes, looks like I can do this:
```
    vim.keymap.set("n", "Y", function()
      return require("yanky").yank({ register = "+" })
    end, { expr = true })
```
