### ISSUE TITLE
FR: last-paste-textobj

### ISSUE THREAD

**Issue by chrisgrieser** [gbprod/yanky.nvim#126]
This plugin does so much when it comes to pasting & indenting, but remembering all those variations does not really fit my workflow. 

I was thinking whether a "last-paste" text-obj could maybe make sense? There are a few vimscript plugins for that, which basically just do `` `[v`] ``. However, it appears that that does not work well with yanky, which somehow "distorts" the resulting selection. In addition, it seems that `` `[v`] `` isn't all too reliable anyway, since various operations like writing the buffer or any other command all result in a change as well, so that `` `[v`] `` would not even reliably select the last paste without yanky.

So my thinking was, the simplest solution would be for yanky to offer such a last-paste-textobj. It should be relatively simple to implement, I think, and it would fit really well with yanky's remaining features as well.

**Comment by gbprod** [comment]
Really interesting
I have a lot of things to do right now but I try to implement this soon :)

**Comment by gbprod** [comment]
Hey @chrisgrieser , I've made something, it's not perfect but I think it's a good start
Feel free to make any feedback !

Thanks

**Comment by chrisgrieser** [comment]
awesome, thank you! Works like a charm 😊

**Comment by chrisgrieser** [comment]
Two minor issues I noticed during working with it:
1. how long exactly is the "last put" textobj valid? I noticed that after editing the pasted lines, I get the "no last put" message. However, one scenario for the last paste object is for example to indent the pasted lines correctly. `>lp` works fine, but another `>lp` gives me the "no last put" message, even though it technically still works.
2. Cannot reliably reproduce the issue, but sometimes after putting, when I do some edit in my buffer, I get a somewhat annoying print message with just the line number of the putted text. 
![Pasted image 2023-10-04 at 14 58 53](https://github.com/gbprod/yanky.nvim/assets/73286100/fc631742-ea91-4cb0-bc7a-acc86d045aab)

**Comment by gbprod** [comment]
Thanks for your feedback:

1. For the moment, I've decide that the textobj is valid until it's modified (to be more precise : until a line before the last line of the region is changed). It could be improved I think but it seems to work for the moment.

2. I've forgot to remove a debug log :sweat_smile: should be fixed now

**Comment by chrisgrieser** [comment]
> I've forgot to remove a debug log 😅 should be fixed now

Thanks!

> For the moment, I've decide that the textobj is valid until it's modified (to be more precise : until a line before the last line of the region is changed). It could be improved I think but it seems to work for the moment.

Yeah, makes total sense. Though some loosening of the restrictions might make sense, as indenting the last paste more than once is not possible right now (`>lp>lp`), which I feel it should 🤔
