### ISSUE TITLE
Hilighlight undo ? 

### ISSUE THREAD

**Issue by gbprod** [gbprod/yanky.nvim#128]

**Comment by NormTurtle** [comment]
do really it support HIGLIGHT UNDO now?

**Comment by gbprod** [comment]
Hey, sorry, I should have precised before closing the ticket.
No, I don't, I've found that there already exist plugins that make it nicely (https://github.com/tzachar/highlight-undo.nvim or https://github.com/yuki-yano/highlight-undo.nvim) so I prefer not to implement this in Yanky.
