### ISSUE TITLE
sqlite option - how to specify its location?

### ISSUE THREAD

**Issue by pmatulis** [gbprod/yanky.nvim#131]
When using the Sqlite option how do use specify the database location? This would be needed when attempting to sync to other hosts.

**Comment by gbprod** [comment]
Hi!

It is currently not possible to choose the sqlite database storage path (see https://github.com/gbprod/yanky.nvim/blob/ef70e4e44095a17ab8611cb6630b727ccee0a271/lua/yanky/storage/sqlite.lua#L19 )

However, it would be quite simple to add an option for this.

**Comment by gbprod** [comment]
Closed by https://github.com/gbprod/yanky.nvim/pull/132
