### ISSUE TITLE
Feature Request: Telescope action to both put item and set register

### ISSUE THREAD

**Issue by kevintraver** [gbprod/yanky.nvim#133]
A new telescope action that simultaneously _puts_ the item and _sets the default register_ at the same time.

Setting the register can be done with `<c-r>`

It would be awesome if there was an option for this to also happen by default on select.

**Comment by kevintraver** [comment]
Could be something like this:

```
function mapping.put_and_set_register(type)
  return function(prompt_bufnr)
    actions.close(prompt_bufnr)
    local selection = action_state.get_selected_entry()
    if vim.api.nvim_get_mode().mode == "i" then
      local cursor_pos = vim.api.nvim_win_get_cursor(0)
      vim.api.nvim_win_set_cursor(0, { cursor_pos[1], math.max(cursor_pos[2] - 1, 0) })
    end
    picker.actions.set_register(utils.get_default_register())(selection.value)
    picker.actions.put(type)(selection.value)
  end
end
```

**Comment by kevintraver** [comment]
Instead of having duplicate code, maybe this could be refactored, and then set as an option:

```
telescope = {
  set_register_on_put = true
}
```

**Comment by gbprod** [comment]
Hey, thanks for your feedback and suggestion.
I've introduced `put_and_set_register` as a default available action.

See #141 ;)
