### ISSUE TITLE
Doesn't work with Telescope

### ISSUE THREAD

**Issue by pmatulis** [gbprod/yanky.nvim#134]
In my nvim configuration I have:

`Plug 'https://github.com/gbprod/yanky.nvim'`

In my telescope configuration I have:

`require('telescope').load_extension('yank_history')`

In my yanky configuration I have:

```
require('yanky').setup({
  ring = {
    history_length = 100,
    storage = "shada",
    sync_with_numbered_registers = true,
    cancel_event = "update",
    ignore_registers = { "_" },
  },
  picker = {
    select = {
      action = nil, -- nil to use default put action
    },
    telescope = {
      use_default_mappings = true, -- if default mappings should be used
      mappings = nil, -- nil to use default mappings or no mappings (see `use_default_mappings`)
    },
  },
  system_clipboard = {
    sync_with_ring = true,
  },
  highlight = {
    on_put = true,
    on_yank = true,
    timer = 500,
  },
  preserve_cursor_position = {
    enabled = true,
  },
})
```

When I yank stuff and invoke `:Telescope yank_history` I see all prior yanks.

However, when I select a result and press Enter, what gets pasted is not the selected contents. The paste is always the most recent yank.

I'm using version `0.10` of neovim.

**Comment by gbprod** [comment]
Can you check if `require('telescope').load_extension('yank_history')` is called after `require('yanky').setup({})` ?

**Comment by pmatulis** [comment]
It wasn't, so I made it so. It didn't help however.

I've noticed that while in Telescope, `Ctrl-n` works as expected by moving the selector forward/down/next. However, `Ctrl-p` (backwards/up/previous) will immediately cause Telescope to exit and paste the most recent yank. So the same end result as described: as if I pressed Enter on any entry.

**Comment by puppyapple** [comment]
same issue here

**Comment by pmatulis** [comment]
So I got most of this to work. I was testing on a remote headless server and my main problem must have been due to a clipboard issue. I can now paste correctly. The only thing that is broken is the **Ctrl-p**. Instead of moving the selector "UP", it acts like **Enter** (pasting the currently selected yank).

**Comment by gbprod** [comment]
Hey, happy to hear that your main problem is solved.

About the `<c-p>` issue, this is how I've set up the default mappings here : https://github.com/gbprod/yanky.nvim#pickertelescopeuse_default_mappings

Maybe it's not a good idea to remap `<c-p>` as it's already used by telescope. I'll open a PR to change this default mapping.

Thanks.

**Comment by puppyapple** [comment]
> Hey, happy to hear that your main problem is solved.
> 
> About the `<c-p>` issue, this is how I've set up the default mappings here : https://github.com/gbprod/yanky.nvim#pickertelescopeuse_default_mappings
> 
> Maybe it's not a good idea to remap `<c-p>` as it's already used by telescope. I'll open a PR to change this default mapping.
> 
> Thanks.

@gbprod In my case, the <c-p> works fine, but whatever I select in the telescope window, it is always the latest history that will be pasted to the cursor position. I use kitty terminal and ssh to a remote Ubuntu. Any idea what may cause this?

**Comment by gbprod** [comment]
Can you open a new issue with your config and the description of your problem ?

**Comment by puppyapple** [comment]
> Can you open a new issue with your config and the description of your problem ?

@gbprod Sure, https://github.com/gbprod/yanky.nvim/issues/138

**Comment by pmatulis** [comment]
@puppyapple Confirmed! Your update makes `Ctrl-p` to navigate the entries. 🍭
