### ISSUE TITLE
Selection of a history in telescope always ends in pasting the latest history record

### ISSUE THREAD

**Issue by puppyapple** [gbprod/yanky.nvim#138]
<img width="1920" alt="image" src="https://github.com/gbprod/yanky.nvim/assets/33118185/ee1a98d0-18cc-4cd6-ba9c-469523de046d">

As showed above,  when I trigger yanky.nvim telescope window, I cycled up and press enter  at the No.13 history, but at the cursor position, the text pasted is always the lastest one(showed below)

<img width="1453" alt="image" src="https://github.com/gbprod/yanky.nvim/assets/33118185/a112644e-9bd1-4a65-9475-9ed6946dd2a7">

The config I use is just the default setting from Lazyvim(https://www.lazyvim.org/extras/coding/yanky)
I am on a remote Ubuntu through SSH, and the terminal is kitty with fish shell.

**Comment by pmatulis** [comment]
I had a similar problem (see #134) when I was interacting with a remote host. I think it has to do with the clipboard. Run `:checkhealth`.

Also try setting this to `false` (by default it is `true`):

```
  system_clipboard = {
    sync_with_ring = false,
  },
```

**Comment by gbprod** [comment]
Ok! I can reproduce this issue using a ssh, I try to find a fix.

**Comment by puppyapple** [comment]
> Ok! I can reproduce this issue using a ssh, I try to find a fix.

Thanks for the work. Looking forward to updates!

**Comment by gbprod** [comment]
Should be fixed now, can you confirm ?

**Comment by puppyapple** [comment]
> Should be fixed now, can you confirm ?

Wonderful, it works well now. Thank you for the quick fix. I close this.
