### ISSUE TITLE
Feature request: Replace with Yanky

### ISSUE THREAD

**Issue by bujesse** [gbprod/yanky.nvim#139]
I use [ReplaceWithRegister](https://github.com/vim-scripts/ReplaceWithRegister) which gives me an operator to replace text with whatever register. 

The common use case is yanking something, then navigating to another part of the code that I want to replace with the thing I just yanked; however in order to not mess with my last register, I have to do a delete/cut to the black hole register, OR specify the 0 register when doing the paste. 

What would be great is to be able to use my Replace with Register, and then YankyCycleBackward to basically replace with the text with any of my previous yanks.

Either way, I can't use Replace with Register in combination with YankyCycleBackward because my last action isn't a YankyPut. I tried to do it like this in a mapping: `"_diw<Plug>(YankyPutBefore)`. However, this does something weird when I try to cycle backwards because it puts the original text back _and_ puts the cycled text before it.

Example: `Yank [H]istory` "_diw\<Plug\>(YankyPutBefore) ->  `Yank [N]ew` \<Plug\>(YankyCycleBackward) -> `Yank [t]elescopeHistory` 

Hope this makes sense. It's a bit difficult to describe.

**Comment by gbprod** [comment]
Hey!
That's pretty clear and I think that [substitute.nvim](https://github.com/gbprod/substitute.nvim) can respond to what you're looking ;)
Have a look and feel free to come back to me if you're missing something
