### ISSUE TITLE
Using the wrong Lua ternary operator

### ISSUE THREAD

**Issue by yutkat** [gbprod/yanky.nvim#14]
The current writing style does not allow the option to be disabled.

```lua
:lua options = { system_clipboard = { sync_with_ring = false}}
:lua print(options.system_clipboard and options.system_clipboard.sync_with_ring or true)
-- output: true
:lua print(options.system_clipboard and "aaa" or "bbb")
-- output: aaa
```

https://github.com/gbprod/yanky.nvim/blob/0155028360e3072fd4f49b58a0d35c6b45c9e64f/lua/yanky/config.lua

**Comment by gbprod** [comment]
🤦‍♂️
I fix this ASAP

**Comment by gbprod** [comment]
I think I fix it, can you update and try again ?

**Comment by yutkat** [comment]
OK, it's working well. Thanks for the fix.

**Comment by gbprod** [comment]
Thank you for raising it !
