### ISSUE TITLE
Text object errors

### ISSUE THREAD

**Issue by MariaSolOs** [gbprod/yanky.nvim#144]
With the addition of the new text object, I've been receiving errors like these:
<img width="1512" alt="image" src="https://github.com/gbprod/yanky.nvim/assets/62502207/14a6b1ea-6747-4652-aa01-46d6ccda68fc">

**Comment by willothy** [comment]
I have been experiencing this as well, usually in insert mode. Sometimes large blocks of spaces appear in the buffer I'm editing as well.

**Comment by MariaSolOs** [comment]
On that note, would it be possible to make the text object optional? I don't plan on using it, so I would prefer this plugin not automatically setting up autocommands.
