### ISSUE TITLE
Bug: Latest commit breaks last-paste-textobj

### ISSUE THREAD

**Issue by chrisgrieser** [gbprod/yanky.nvim#146]
the last commit (7427e77) seems to have broken the last-paste textobject for me, I now always get the "no last paste" message.

cc @MariaSolOs (sorry)

**Comment by MariaSolOs** [comment]
@chrisgrieser did you enable the text object setting?

**Comment by MariaSolOs** [comment]
You have a typo in your config. It's `textobj`, not `textobjs`: https://github.com/chrisgrieser/.config/blob/ece7b09a7ce37d57ac7f3cb8edbc0ea2b1fad7d7/nvim/lua/plugins/editing-support.lua#L275

**Comment by chrisgrieser** [comment]
> You have a typo in your config. It's textobj, not textobjs:

Yeah, I also noticed that one an hour ago, but it does not seem to make a difference

**Comment by MariaSolOs** [comment]
@chrisgrieser could you please confirm if #147 fixed this issue?

**Comment by chrisgrieser** [comment]
yep, can confirm that it works now
