### ISSUE TITLE
Question: is there lua API to get last yank/copy text, and get all the yank/copy history?

### ISSUE THREAD

**Issue by linrongbin16** [gbprod/yanky.nvim#153]
Hi,

I'm writing a fzf-based plugin [fzfx.nvim](https://github.com/linrongbin16/fzfx.nvim), and I want to get the yank/copy text (and in the future I even want the yank/copy buffer filename & lineno info etc) from yanky.nvim, so I don't have to implement the yank relate logic again.

Is there lua API to get the latest yank/copy test? And get all the yank/copy history?

**Comment by gbprod** [comment]
Yes, you can look try with `require("yanky.history").all()` and look at the [history api](https://github.com/gbprod/yanky.nvim/blob/main/lua/yanky/history.lua). This will returns a collection of objects with `regcontents`, `regtype` and `filetype`.

You can also look at the [telescope plugin](https://github.com/gbprod/yanky.nvim/blob/main/lua/yanky/telescope/yank_history.lua) for inspiration ;)

**Comment by linrongbin16** [comment]
thanks
