### ISSUE TITLE
Wrong behavior of telescope.mapping.put actions

### ISSUE THREAD

**Issue by bak-t** [gbprod/yanky.nvim#160]
# Brief
Currently action from `mapping.put('p')` puts text before cursor position & `mapping.put('P')` puts text before character that precedes cursor position.

# Steps to reproduce

## Paste after
1. Set cursor to desired position
2. Run Telescope UI for Yanky History: `:lua require("telescope").extensions.yank_history.yank_history()`
3. Select item & press `C-Enter`
### Actual result
Item is inserted before cursor position.
### Expected result
Item is inserted after cursor position.

## Paste before
1. Set cursor to desired position
2. Run Telescope UI for Yanky History: `:lua require("telescope").extensions.yank_history.yank_history()`
3. Select item & press `S-Enter`
### Actual result
Item is inserted before character that precedes cursor position.
### Expected result
Item is inserted before cursor position.

# Additional details
**Neovim version:** 0.9.4
**Plugin version:** 2.0.0
**Config for the plugin:**
```lua
	config = function()
		local utils = require("yanky.utils")
		local mapping = require("yanky.telescope.mapping")
		local action = {
			paste_after = mapping.put('p'),
			paste_before = mapping.put('P'),
			set_default_register = mapping.set_register(utils.get_default_register()),
			delete = mapping.delete(),
		}

		require('yanky').setup({
			system_clipboard = {
				sync_with_ring = false,
			},
			picker = {
				telescope = {
					use_default_mappings = false,
					mappings = {
						default = action.paste_after,
						i = {
							['<S-CR>'] = action.paste_before,
							['<C-CR>'] = action.paste_after,
							['<M-r>'] = action.set_default_register,
							['<M-d>'] = action.delete,
						},
						n = {
							['<leader>p'] = action.paste_after,
							['<leader>P'] = action.paste_before,
							['<S-CR>'] = action.paste_before,
							['<leader>r'] = action.set_default_register,
							['<leader>d'] = action.delete,
						},
					},
				}
			},
		})
	end
```

**Comment by gbprod** [comment]
Thanks for reporting this issue, for the moment, I'm not able to reproduce this...
It could comes from another plugin you have installed, car you try without other plugins ?

**Comment by bak-t** [comment]
I tried with minimum set of plugins (yanky.nvim, telescope.nvim, plenary.nvim, lazy.nvim) - the bug is still reproduced. Here is the config I used:
[nvim_min.zip](https://github.com/gbprod/yanky.nvim/files/13391289/nvim_min.zip).

Also I forget to mention that I used Windows 10.

**Comment by bak-t** [comment]
Confirming that fix works for me (both GUI & Terminal version).

**Comment by gbprod** [comment]
Great ! 
I merge :)
Thanks

**Comment by nikbrunner** [comment]
I am facing this issue again, but only when the rest of the line is empty. The text pastes before the cursor, contrary to what I expect based on the default settings. It pastes correctly when there is content after the cursor.


https://github.com/gbprod/yanky.nvim/assets/46924729/52960b9f-b29d-46c7-97b2-d900a79e5c99

This is my lazy config:

```lua
local M = {}

---@type LazyPluginSpec
M.spec = {
    "gbprod/yanky.nvim",
    dependencies = { "chrisgrieser/cmp_yanky" },
    opts = {},
    keys = {
        { "<c-p>", "<Plug>(YankyPreviousEntry)" },
        { "<c-n>", "<Plug>(YankyNextEntry)" },

        { "p", "<Plug>(YankyPutAfter)", mode = { "n", "x" } },
        { "P", "<Plug>(YankyPutBefore)", mode = { "n", "x" } },

        {
            "<C-r>",
            "<cmd>Telescope yank_history theme=cursor previewer=false<cr>",
            desc = "[Y]ank History",
            mode = { "i", "n", "x" },
        },
    },
}

return M.spec
```

If i should open a new issue for this, please let me know.
