### ISSUE TITLE
YankyPutAfter vs YankyGPutAfter

### ISSUE THREAD

**Issue by davidsteinberger** [gbprod/yanky.nvim#167]
I've been playing around w/ yanky and really like it. Well done!  
I'm not sure if this is the right place to ask but I do not get the difference between `YankyPutAfter` and `YankyGPutAfter`. 
I initially thought that the latter would preserve the selected text, but for me it looks like as if both are doing the same thing in normal and visual mode. What am I missing?

**Comment by gbprod** [comment]
Hey!
If you read `:help gp` : ` Just like "p", but leave the cursor just after the new text.` :)
