### ISSUE TITLE
Ability to insert something into the kill ring through lua?

### ISSUE THREAD

**Issue by kvietcong** [gbprod/yanky.nvim#17]
Is there any way to have a function to insert arbitrary values into the kill ring? I have a message selector that inserts a value into the " register and would love for it to also insert it into yanky.

**Comment by gbprod** [comment]
Hello,
You can do it using : 
```lua
require('yanky').history.push({
    regcontents="test", 
    regtype="v" -- or "V" or "b",
})
```
:)

**Comment by kvietcong** [comment]
Thank you so much! Thanks for the plugin too, makes putting so much easier for me
