### ISSUE TITLE
slow neovim with :global

### ISSUE THREAD

**Issue by endir** [gbprod/yanky.nvim#187]
whenever I have yanky enabled and do :g/foo/delete    nvim is very slow. I think yanky is storing each line in the database. How do I disable this behaviour?

**Comment by gbprod** [comment]
Can you share your config please?

**Comment by endir** [comment]
￼Thank you! here is my config

require("yanky").setup({
  ring = {
    history_length = 300,
    storage = "sqlite",
    sync_with_numbered_registers = true,
    cancel_event = "update",
    ignore_registers = { "_" },
  },
  system_clipboard = {
    sync_with_ring = true,
  },
})

vim.keymap.set({"n","x"}, "p", "<Plug>(YankyPutAfter)")
vim.keymap.set({"n","x"}, "P", "<Plug>(YankyPutBefore)")
vim.keymap.set("n", "<c-p>", "<Plug>(YankyCycleForward)")
vim.keymap.set("n", "<c-n>", "<Plug>(YankyCycleBackward)")
require("telescope").load_extension("yank_history")

**Comment by gbprod** [comment]
Do you have the same problem using shada as storage ?

**Comment by endir** [comment]
With shada I cannot see the problem. Would it be possible to disable yanky on :global cmd?

**Comment by gbprod** [comment]
Sorry for the late answer.
Unfortunately, it's not possible to disable yanky for `global` commands.
I'll suggest to stop using `sqlite` storage as it cause a lots of performance issues... and maybe use `:g/foo/normal! delete` to disable yanky delete mapping.
