### ISSUE TITLE
Conflict with 'nvim-treesitter/nvim-treesitter-context' and 'p00f/nvim-ts-rainbow'

### ISSUE THREAD

**Issue by Kaiser-Yang** [gbprod/yanky.nvim#190]
When telescope with these two plugins, paste through `Telescope yank_history` will cause errors:
![image](https://github.com/user-attachments/assets/b7e4ff4a-69bf-4998-a1b1-b8554467c1da)

The minimal to reproduce this: [yanky-reproduce](https://github.com/Kaiser-Yang/dotfiles/tree/yanky-reproduce)

Step to reproduce:
1. Copy the directory:
![image](https://github.com/user-attachments/assets/1cf9f9fe-c428-419d-b688-5c6d8adb91f6)
2. Yank something with some brackets
3. Open a file with some brackets and use `Telescope yank_history` to chose (`<c-j>` and `<c-k>` can navigate) the yanked one then press `<cr>`

**Comment by gbprod** [comment]
Strange, I have to look at this

**Comment by gbprod** [comment]
Seems to be only an issue with `p00f/nvim-ts-rainbow`, as it's no longer maintained, I don't think it's necessary to investigate more ;)
