### ISSUE TITLE
Clipboard hangs when trying to enable OSC 52

### ISSUE THREAD

**Issue by kescobo** [gbprod/yanky.nvim#191]
Related to #113

I'm using the LazyVim configuration, which includes yanky, but I need clipboard support on my remote server, and would like to use `wezterm`, which [doesn't do X forwarding](https://github.com/wez/wezterm/discussions/5231). The solution seems to be to force the usage of OSC52 so that I can copy/paste to my local clipboard. 

However, when I add the suggested

```
vim.g.clipboard = {
  name = "OSC 52",
  copy = {
    ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
    ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
  },
  paste = {
    ["+"] = require("vim.ui.clipboard.osc52").paste("+"),
    ["*"] = require("vim.ui.clipboard.osc52").paste("*"),
  },
}
```

to `lua/config/options.lua`, any time I open a file buffer, I get a message "Waiting for OSC 52 response from the terminal." followed by "Timed out waiting for a clipboard response from the terminal". Then, when I attempt to yank, nothing gets added to the register.

If I disable loading `yanky`, I don't get the timeout when opening a buffer, and yanking works as expected. However, I don't know that this is really `yanky`'s fault, since when I paste, I get the same timepoint message (though after it times out, the pasting happens).

**Comment by kescobo** [comment]
Sorry - a bunch of this is a red herring. If I do a totally blank `init.lua` other than 

```
vim.opt.clipboard = "unnamedplus"

vim.g.clipboard = {
  name = "OSC 52",
  copy = {
    ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
    ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
  },
  paste = {
    ["+"] = require("vim.ui.clipboard.osc52").paste("+"),
    ["*"] = require("vim.ui.clipboard.osc52").paste("*"),
  },
}
```

and the same thing happens with alacritty over ssh, so it's not wezterm's fault either. I'll open an issue in nvim

**Comment by kescobo** [comment]
For anyone encountering this in the future, this worked for me: https://github.com/neovim/neovim/discussions/28010#discussioncomment-9877494

```
vim.o.clipboard = "unnamedplus"

local function paste()
  return {
    vim.fn.split(vim.fn.getreg(""), "\n"),
    vim.fn.getregtype(""),
  }
end

vim.g.clipboard = {
  name = "OSC 52",
  copy = {
    ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
    ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
  },
  paste = {
    ["+"] = paste,
    ["*"] = paste,
  },
}
```

**Comment by allpan3** [comment]
This workaround apparently breaks the yanky - I'm no longer able to cycle through the history. After some debugging I found that `setreg` function isn't able to set the `"+` register, which isn't the case when I use the osc52 paste.

But I'm having trouble figuring the out the issue beyond this observation.

**Comment by kiyoon** [comment]
I solved it by ignoring the clipboard registers on yanky setup.

```lua
local yanky = require "yanky"
yanky.setup {
  ring = {
    ignore_registers = { "_", "+", "*" },
  },
  highlight = {
    on_put = true,
    on_yank = true,
    timer = 300,
  },
}
```

**Comment by Dioswilson** [comment]
> I solved it by ignoring the clipboard registers on yanky setup.

Didn't work for me, still can't cycle over ring buffer, it always pastes the last one even with `YankyRingHistory` and manually selecting

**Comment by MartinLoeper** [comment]
I observed the same issue. I think this issue should either be reopened or we need a separate issue. I was not able to make yanky work when using osc 52

**Comment by pkarlovsek** [comment]
Did anyone figure out how to make yanky work with OSC 52?
