### ISSUE TITLE
Feature: wsl support! 

### ISSUE THREAD

**Issue by gaoqiangks** [gbprod/yanky.nvim#196]
When pasting text from windows system clipboard, there's always a `^M` at the end of each line. Hoping for an option that yanky will automatically remove the `^M` if it is running in WSL when pasting.

**Comment by shubhamkumar13** [comment]
Yeah I'm getting a similar issue

**Comment by gbprod** [comment]
I'll work on this today, sorry for the late answer

**Comment by gbprod** [comment]
Hi!
I've introduced a new option with this PR : https://github.com/gbprod/yanky.nvim/pull/203
Can you tell me if it works for you, you can find how to set this up here : https://github.com/gbprod/yanky.nvim?tab=readme-ov-file#-integrations

**Comment by RayGuo-ergou** [comment]
Hi @gbprod I think there's a typo

https://github.com/gbprod/yanky.nvim/pull/203/files#diff-8fb36e90db2e436c760f5a4361720fa08e811f54c646cd2038f667e9e3733bfaR100-R102

`permament_wrapper` -> `permanent_wrapper`😀

Have tested, after fix this typo new line removed, thank you!

**Comment by gbprod** [comment]
:facepalm: thax, it's fixed
