### ISSUE TITLE
Breaking changes and News

### ISSUE THREAD

**Issue by gbprod** [gbprod/yanky.nvim#2]
I will log here news and api changes, feel free to subscribe to this issue.

**Comment by sangdth** [comment]
The plugin looks cool, I will try it soon. Thanks for the works! <3

**Comment by gbprod** [comment]
Introducing `picker` functionnality.
This allows to select a item in yank history using `vim.ui.select` or `Telescope`.

**Comment by gbprod** [comment]
BC : Increase neovim required version to `0.7.0`

**Comment by gbprod** [comment]
Introducing command to clear yank history : `YankyClearHistory`

**Comment by gbprod** [comment]
Introducing new actions to remove entries from yank history using Telescope picker.

**Comment by gbprod** [comment]
**Version tagged v0.3.0**

**Special put**
Introduce special put moves [https://github.com/gbprod/yanky.nvim/pull/33] see https://github.com/gbprod/yanky.nvim#%EF%B8%8F-special-put

**Yanking**
Introduce option to set the register that will be used for yank (https://github.com/gbprod/yanky.nvim/pull/24)

**Telescope**
Introduce an action to set register content from selected item (https://github.com/gbprod/yanky.nvim/pull/23)

**Comment by gbprod** [comment]
Introduce `sqlite` storage for yank ring https://github.com/gbprod/yanky.nvim/pull/55

**Comment by gbprod** [comment]
introduce Joined/Charwise/Blockwise special puts

**Comment by farzadmf** [comment]
@gbprod I was subscribed to this issue. Does the issue being closed somehow mean that the plugin is not going to be maintained anymore? 🤔

**Comment by gbprod** [comment]
Hi @farzadmf !
I continue to maintain this plugin but I think I will stop filling this issue, I will instead use the releases for this.
😉
