### ISSUE TITLE
Adding `GPut<>Indent` commands

### ISSUE THREAD

**Issue by dgmora** [gbprod/yanky.nvim#200]
I've noticed there's no `GPut<>Indent` commands, could it be implemented or is there a reason for its absence?

I was trying to copy a block, and getting it indented with the cursor after it (That'd be `YankyGPutAfterIndentLinewise`)

**Comment by gbprod** [comment]
I take a look

**Comment by gbprod** [comment]
Yes, it doesn't exist but you can do this using : 

```
vim.keymap.set("n", ")gp", function()
    require("yanky").put("gp", false, require("yanky.wrappers").linewise(require("yanky.wrappers").change("==")))
end, { silent = true })
```
