### ISSUE TITLE
How to put a block of text (multiline) between 2 character (instead of next line) like C-r " in insert mode

### ISSUE THREAD

**Issue by DeepReef11** [gbprod/yanky.nvim#202]
For instance

```
<div></div>
```
I would like to put 
```
<div>
text
</div>
```
In the previous div, so it would result in:

```
<div>
<div>
text
</div></div>
```

Instead of
```
<div></div>
<div>
text
</div>
```

**Comment by gbprod** [comment]
Hi!
you can use [Special Put](https://github.com/gbprod/yanky.nvim?tab=readme-ov-file#-special-put) for that.
You can use something like : 

```lua 
vim.keymap.set("n", ")p", "<Plug>(YankyPutAfterCharwise)")
```

**Comment by DeepReef11** [comment]
Thank you, that's exactly it!
