### ISSUE TITLE
Feature Request: Ability to optional send to different registers

### ISSUE THREAD

**Issue by kevintraver** [gbprod/yanky.nvim#22]
It would be awesome to send to specific registers when using `YankyYank`.

I use https://github.com/christoomey/vim-system-copy, and have different mappings for the _normal_ register and the _system (global)_ register. 

It would be awesome to have separate keymaps, but also use the _preserve cursor feature_! for both.

**Comment by gbprod** [comment]
Good idea, I'll try to implement this next week!

**Comment by gbprod** [comment]
You have 2 solutions now : 

You can set a mapping like : `vim.keymap.set("n", "cp", '"a<Plug>(YankyYank)', {})`, then `cp` will yank to `"a` register.

Following to [this PR](https://github.com/gbprod/yanky.nvim/pull/24), you can also do : 
```lua
vim.keymap.set("n", "cp", function() 
    return require("yanky").yank({ register = "a" }) 
end, { expr = true })
```

Thanks for your feedback !

**Comment by kevintraver** [comment]
Awesome!! Thank you!
