### ISSUE TITLE
[Bug] `:YankyRingHistory` puts in last yanked position, instead of cursor

### ISSUE THREAD

**Issue by luiz00martins** [gbprod/yanky.nvim#25]
Executing `:YankyRingHistory` will put the selected text on the last position you yanked from, substituting the last text yanked.

My current config:
```lua
use{
	'gbprod/yanky.nvim',
	config = function()
		require("yanky").setup({
			picker = {
				select = {
					action = require("yanky.picker").actions.put("p"),
				},
				telescope = {
					mappings = nil, -- nil to use default mappings
				},
			},
		})
	end
}
```

**Comment by gbprod** [comment]
That's an issue introdiced by this commit in telescope : https://github.com/nvim-telescope/telescope.nvim/commit/3eb90430b61b78b707e8ffe0cfe49138daaddbcc

**Comment by gbprod** [comment]
This should be fixed by https://github.com/gbprod/yanky.nvim/pull/26
Thanks for reporting
