### ISSUE TITLE
conditional map `<c-n> & <c-p`

### ISSUE THREAD

**Issue by aceforeverd** [gbprod/yanky.nvim#30]
so I want e.g `<c-n>` to fallback to normal `ctrl_n` or something if it is not in a paste/cycle state

I write something like
```lua
local function map_c_n()
  if require('yanky').ring.state then
    require('yanky').cycle(1)
  else
    vim.cmd[[execute "normal! \<c-n>"]]
  end
end
```

to remap `<c-n>` but it seems `ring.state` can only back to `nil` if line content is changed. Will it possible back to `nil` also if cursor moved out of pasted line ?

**Comment by gbprod** [comment]
Interesting!
I think I can introduce an option to chose between "cursor moved" or "content changed" event (because I prefer "content changed event 😉)

I'll try to add this in the next few days!

**Comment by gbprod** [comment]
Hi @aceforeverd ! 
I've made something here : https://github.com/gbprod/yanky.nvim/pull/32
Do you want to try before I merge ?

**Comment by gbprod** [comment]
Thanks for feedbacks !

I've introduced `require('yanky').can_cycle()` method (more meaningful for me than `is_in_ring`)
I've also updated documentation ;)

I'll make more tests and I'll merge after

**Comment by aceforeverd** [comment]
> 

awesome :)

**Comment by anuvyklack** [comment]
You can use [keymap-amend](https://github.com/anuvyklack/keymap-amend.nvim) plugin for this mapping:
```lua
keymap.amend('n', '<C-p>', function(original)
   if yanky.can_cycle() then                 
      yanky.cycle(-1)                        
   else                                      
      original()                             
   end                                       
end)                                         
                                             
keymap.amend('n', '<C-n>', function(original)
   if yanky.can_cycle() then                 
      yanky.cycle(1)                         
   else                                      
      original()                             
   end                                       
end)                                         
```
It plays well with [vim-visual-muilti](https://github.com/mg979/vim-visual-multi).
