### ISSUE TITLE
Feature request: force line-wise paste above or below current line

### ISSUE THREAD

**Issue by drinkitup777** [gbprod/yanky.nvim#31]
One of `vim-unimpaired`'s useful features is to force pasting below or above the current line, while preserving indents. It's very useful, but not usable with `yanky`.

[Here are the keybinds.](https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt#L100)

**Comment by gbprod** [comment]
That's a really interesting feature, I think I can do something for that next week 😉

**Comment by drinkitup777** [comment]
It's pasting on the right line, but I don't think the indenting is acting right. If you do a character-wise yank, it always acts as if it's coming from indent level 0. For example, if you yank a word from a line and `>p`, it will be put on the next line with indent 1, no matter the indent level of the line it was yanked from. It's the same for `[p` and `]p` ... etc.

*Side: congrats on joining the `[p` club 🤓*

**Comment by gbprod** [comment]
Thanks for the feedback!!!
I've made some updates.
I've changed `<Plug>` names, I think you'll I've something really close to `vim-unimpaired`:

```lua
vim.keymap.set("n", "]p", "<Plug>(YankyPutIndentAfterLinewise)", {})
vim.keymap.set("n", "[p", "<Plug>(YankyPutIndentBeforeLinewise)", {})
vim.keymap.set("n", "]P", "<Plug>(YankyPutIndentAfterLinewise)", {})
vim.keymap.set("n", "[P", "<Plug>(YankyPutIndentBeforeLinewise)", {})

vim.keymap.set("n", ">p", "<Plug>(YankyPutIndentAfterShiftRight)", {})
vim.keymap.set("n", "<p", "<Plug>(YankyPutIndentAfterShiftLeft)", {})
vim.keymap.set("n", ">P", "<Plug>(YankyPutIndentBeforeShiftRight)", {})
vim.keymap.set("n", "<P", "<Plug>(YankyPutIndentBeforeShiftLeft)", {})

vim.keymap.set("n", "=p", "<Plug>(YankyPutAfterFilter)", {})
vim.keymap.set("n", "=P", "<Plug>(YankyPutBeforeFilter)", {})
```

**Comment by drinkitup777** [comment]
Just tested, and all seems to be in working order. Thanks for the quick implementation!

**Comment by TamaMcGlinn** [comment]
Could you increase the visibility of this by suggesting those maps in the README? I think people who are used to vim-unimpaired expect this to "just work", and not to have to search the issues for 'unimpaired' - which I only did because I thought there was a bug similar to #19
