### ISSUE TITLE
Does not work with plugins that try to hijack P, p keys

### ISSUE THREAD

**Issue by shivanthzen** [gbprod/yanky.nvim#38]
I ran into conflicts when I was trying to use [tmux.nvim](https://github.com/aserowy/tmux.nvim) since this plugin also tries to hijack P key

**Comment by gbprod** [comment]
Thanks for reporting this issue.
Can you provide a minimal config ?
Thanks

**Comment by gbprod** [comment]
If you want to keep both plugins behavior, you should do something like : 

```lua
vim.keymap.set("n", "p", function()
  yanky.put(type, false, function(state, callback)
    require("tmux").sync_registers('p')
    callback(state)
  end)
end, { silent = true })
```
