### ISSUE TITLE
Feature Request: add canCycle() support

### ISSUE THREAD

**Issue by changyiyao** [gbprod/yanky.nvim#41]
Just like [yoink#canSwap()](https://github.com/svermeulen/vim-yoink#faq) resolve potential conflict with other famous plugins. (aka. visual-multi-cursor)

**Comment by gbprod** [comment]
Hi !
You already have a lua function to do that : `require("yanky").can_cycle()`
Does it makes the job for you ?

**Comment by changyiyao** [comment]
🥳 It makes! Duplicate #30
