### ISSUE TITLE
[BUG] `[p` and `]p` history items get inserted character-wise

### ISSUE THREAD

**Issue by drinkitup777** [gbprod/yanky.nvim#44]
The expected behavior for `[p` and `]p` would be that every item is forced line-wise, but any character-wise yanks beyond the first item get inserted character-wise.

![Animation](https://user-images.githubusercontent.com/59168253/186263336-43264560-cb10-4f05-ad1b-f5561364a543.gif)

Steps to reproduce:

1. Yank a character-wise string
2. `[p`
3. Cycle through put history with `<C-p>`
4. Observe that character-wise history items show up on the current line

**Comment by gbprod** [comment]
That's right, I'll work on a fix soon.
Thanks for reporting this issue!

**Comment by gbprod** [comment]
I've made something here #45 if you want to test before I merge :)

**Comment by gbprod** [comment]
#45 fix the issue

**Comment by drinkitup777** [comment]
Tested, and working on my end 👌
