### ISSUE TITLE
Clipboard error : Target STRING not available

### ISSUE THREAD

**Issue by karlc1** [gbprod/yanky.nvim#46]
I get the message `Clipboard error : Target STRING not available` when starting neovim with this plugin setup. The message does not appear when I disable yanky in my config. 

I found this issue on neovims repo: https://github.com/neovim/neovim/issues/2642 

Where the last comment states: 

```
On the off chance someone else still sees this error, you could be using an older yank plugin like https://github.com/svermeulen/vim-easyclip

Moving to something newer like https://github.com/svermeulen/vim-cutlass will avoid these issues.
```

So I guess there is some configuration that needs to be done plugin side to avoid this

**Comment by gbprod** [comment]
Hi @karlc1,
That's a [xclip related issue](https://github.com/astrand/xclip/issues/38) (see https://github.com/neovim/neovim/issues/15478), you can avoid this using `xsel` instead of `xclip` :

```lua
-- init.lua
vim.g.clipboard = {
  name = "xsel_override",
  copy = {
    ["+"] = "xsel --input --clipboard",
    ["*"] = "xsel --input --primary",
  },
  paste = {
    ["+"] = "xsel --output --clipboard",
    ["*"] = "xsel --output --primary",
  },
  cache_enabled = 1,
}
```
