### ISSUE TITLE
'Y' does not copy whole line

### ISSUE THREAD

**Issue by damanis** [gbprod/yanky.nvim#47]
'yy' works properly - copy whole line.
The command 'Y' is synonym of 'yy', but it copies line from cursor to end of line.

**Comment by gbprod** [comment]
This is not a Yanky feature, it's Neovim defaults mappings : https://neovim.io/doc/user/vim_diff.html#default-mappings.

Just unmap `Y`

**Comment by damanis** [comment]
Yes, my mistake
