### ISSUE TITLE
Feature request: auto format on paste

### ISSUE THREAD

**Issue by gbcreation** [gbprod/yanky.nvim#49]
One of the `vim-easyclip`'s useful features is to automatically format text immediately after paste. It's very useful, but not usable with yanky.

It is slightly different than `PutIndent*` because the pasted lines do not necessarily have the same indentation as the current line. They can have an extra indent depending on the context.

For example, if the text `let a = 1` is pasted when the cursor is on the second line in this example:

```javascript
function f(flag) {
    if (flag === true) { // <= cursor is on this line
    }
}
```

the expected result would be:

```javascript
function f() {
    if (flag === true) {
        let a = 1
    }
}
```

with `YankyPutIndentAfter`, we get this:

```javascript
function f() {
    if (flag === true) {
    let a = 1
    }
}
```

**Note:** the request is not to change the behavior of `YankyPutIndent*` but to add a new option to auto format pasted lines.

**Comment by gbprod** [comment]
Hi ! Thanks for idea.
I think I can do something.

**Comment by gbprod** [comment]
I've you tried using `<Plug>(YankyPutAfterFilter)` (usualy mapped to `=p`) ?
I think it does what you expect.

**Comment by gbcreation** [comment]
Unfortunately `<Plug>(YankyPutAfterFilter)` does not the job. When I yank an indented line and paste it after an empty line, the indentation is removed (the first character is at column zero). Hitting `==` after that reindent the pasted line correctly.

**Comment by gbcreation** [comment]
Unfortunately `<Plug>(YankyPutAfterFilter)` does not the job. When I yank an indented line and paste it after an empty line, the indentation is removed (the first character is at column zero). Hitting `==` after that reindent the pasted line correctly.

**Comment by gbcreation** [comment]
I'm sorry, it seems I forgot to run `:PackerCompile` after changing my configuration of Yanky. After running this command, using `<Plug>(YankyPutAfterFilter)` works perfectly.

Thank you for you answer.

**Comment by gbprod** [comment]
😉👍
