### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by jaidetree** [gbprod/yanky.nvim#50]
Given a config like the following packer config:

```fennel
(use {1 "gbprod/yanky.nvim"
      :config #(let [yanky (require :yanky)]
                  (yanky.setup))})

(use {1 "telescope-nvim/telescope.nvim"
      :requires ["gbprod/yanky.nvim"]
      :config #(let [ts (require :telescope)]
                  (ts.setup {})
                 
                  (ts.load_extension "yank_history"))})
```

## Expected

I would expect that yanky initializes before telescope does given that yanky is a dependency of telescope. 

## Actual

It seems like a race condition for which :config function runs first. Some loads it's fine, other times I get an error about yank_history not existing at the time the `load_extension` call fires.

It's possible I'm just being a super noob here and using the wrong packer API here but based on the docs that seems like how it should work?

Please let me know if the fennel is too unfamiliar, I can convert it back to lua if needed.

**Comment by gbprod** [comment]
Hey !

Thanks for reporting this issue :)

I've you tried to use `after` or `before` config ? https://github.com/wbthomason/packer.nvim#sequencing

Could be something like : 

```fennel
(use {1 "gbprod/yanky.nvim"
      :before ["telescope-nvim/telescope.nvim"]
      :config #(let [yanky (require :yanky)]
                  (yanky.setup))})
```

Or

```fennel
(use {1 "telescope-nvim/telescope.nvim"
      :requires ["gbprod/yanky.nvim"]
      :after ["gbprod/yanky.nvim"]
      :config #(let [ts (require :telescope)]
                  (ts.setup {})
                 
                  (ts.load_extension "yank_history"))})
```

**Comment by eccentric-j** [comment]
That helps a lot thanks! I skipped the sequencing section expecting it to be part of the dependencies config and missed that. I was afraid that it was just me not using packer correctly. Sorry about that 😅

One note though is this issue seems to only happen with yanky and telescope for example the file browser plug-in for telescope so maybe there is room to smooth that out? Or does yanky have to be setup before the extension registers?

**Comment by gbprod** [comment]
Yep, I'll make some test to improve this (I keep this issue open)

**Comment by jdsutherland** [comment]
I'm seeing the same issue in lazy with yanky set as a dependency.
