### ISSUE TITLE
Highlight on yank now in neovim

### ISSUE THREAD

**Issue by simonmandlik** [gbprod/yanky.nvim#61]
Nvim now natively provides `vim.highlight.on_yank()`, which seems to have identical outcome as `highlight.on_yank`. Perhaps I would consider setting `highlight.on_yank` off by default so that it doesn't clash out of the box with config of others. 

What do you think?

**Comment by gbprod** [comment]
Thanks for your feedback

Yanky use `vim.highlight.on_yank()` for this feature : https://github.com/gbprod/yanky.nvim/blob/main/lua/yanky/highlight.lua#L17
The aim is to simplify user-side config as you don't have to create autocmd, highlight group, etc... and everything works out of the box, so I prefer to let this setting on by default.
Anyway, I think I should improve documentation about this.

**Comment by simonmandlik** [comment]
Oh, I see. Thanks!
