### ISSUE TITLE
Feature Request: Preview

### ISSUE THREAD

**Issue by curtbushko** [gbprod/yanky.nvim#65]
Good day!  I love this plugin and use it every day but there is 1 feature that I think would push it over the top: previews in the Ring History similar to [neoclip](https://github.com/AckslD/nvim-neoclip.lua)

I do not know how difficult that would be with telescope but I think it'd be great!

Thanks again for the great work on this plugin!

**Comment by gbprod** [comment]
Hey! Thanks for your feedback!

You can already have Preview like Neoclip if you use Telescope extension of yanky history picke :  https://github.com/gbprod/yanky.nvim#-yank-history-picker

Just add `require("telescope").load_extension("yank_history")` to your config and then `:Telescope yank_history`.

Is this that your looking for ?

**Comment by curtbushko** [comment]
Hey!  I was thinking something different than what is there now. Unless it is my telescope config, my preview looks like this:

<img width="644" alt="Screen Shot 2022-11-19 at 11 29 04 AM" src="https://user-images.githubusercontent.com/431893/202861336-d64c34f2-a4a0-4dc7-b5e7-bb182e78f621.png">

while neoclip is like the image below and shows the entire preview separately.

![140090515-83a08f0f-85f9-4278-bcbe-48e4d8442ace](https://user-images.githubusercontent.com/431893/202861438-75dcc740-b041-439c-9ed2-c4a78d636dd6.png)

I find the neoclip preview to be quite nice when you have large multi-line yanks. It looks quite impressive when you are screen sharing too!

**Comment by gbprod** [comment]
I think it should be your telescope settings, can you provide your config ?

**Comment by curtbushko** [comment]
What does your preview look like?

I am using AstroNvim: https://github.com/AstroNvim/AstroNvim/blob/main/lua/configs/telescope.lua

**Comment by gbprod** [comment]
My preview looks like with neoclip. 
I'll take a look on Monday ;)

**Comment by curtbushko** [comment]
I figured it out and it was all in my own config. I wasn't telescope loading yanking in the correct place and it looked like it was working because of :YankRingHistory but not :Telescope yank_history.

100% my fault!  Thanks for the help!

**Comment by gbprod** [comment]
👍👍👍
