### ISSUE TITLE
Ability to do character-, line-, or block-wise paste

### ISSUE THREAD

**Issue by thecontinium** [gbprod/yanky.nvim#66]
Hi 

Thanks for yanky. 

“I occasionally do a linewise yank, and then want to insert that yanked text in the middle of some other line (or vice versa).”

I use the [UnconditionalPaste](https://github.com/inkarkat/vim-UnconditionalPaste) plugin for this and would like to use some of it’s functionality from yanky. 

I can’t see how but perhaps it’s possible to use now with config changes ?

Would you see this as integration or would you consider adding the ability to have options do the character-, line-, or block-wise paste ?

Cheers

**Comment by gbprod** [comment]
Hey!

Thanks for your feedback, it seems that is something that could be implements in yanky. I have to try [UnconditionalPaste](https://github.com/inkarkat/vim-UnconditionalPaste) to see how it works.

By the way, In Yanky, you already have a [linewise paste](https://github.com/gbprod/yanky.nvim#%EF%B8%8F-special-put), does it works like in UnconditionalPaste ?

**Comment by thecontinium** [comment]
Hi

Yes you already have the Linewise option. e.g. if I yank a word, or visually select some text, and then paste Linewise it put’s it on another line rather than ( the default ) of inserting after/before the “character" where the cursor is.

I would like go the other way.

When I have yanked a line I would like to be able to “force" it to paste/insert after/before the “character" where the cursor is.

I currently have these options setup for UnconditionalPaste that allow “forcing" of the paste.

``` vim
  nmap Pc <Plug>UnconditionalPasteCharBefore
  nmap pc <Plug>UnconditionalPasteCharAfter
  nmap Pl <Plug>UnconditionalPasteLineBefore
  nmap pl <Plug>UnconditionalPasteLineAfter
```

Perhaps, if you could add the yanky option (say) “CharWise” with the usual before and after that would be great.
Having that then available as an option from Telescope etc etc ...


Cheers

--
The Continium


On 6 December 2022 at 08:01:10, gbprod ***@***.******@***.***>) wrote:

Hey!

Thanks for your feedback, it seems that is something that could be implements in yanky. I have to try UnconditionalPaste<https://github.com/inkarkat/vim-UnconditionalPaste> to see how it works.

By the way, In Yanky, you already have a linewise paste<https://github.com/gbprod/yanky.nvim#%EF%B8%8F-special-put>, does it works like in UnconditionalPaste ?

**Comment by gbprod** [comment]
Hi !

> Yes you already have the Linewise option. e.g. if I yank a word, or visually select some text, and then paste Linewise it put’s it on another line rather than ( the default ) of inserting after/before the “character" where the cursor is.

I think it's because yu use `<Plug>(YankyPutIndentAfterLinewise)` instead of `<Plug>(YankyPutAfterLinewise)`.

> When I have yanked a line I would like to be able to “force" it to paste/insert after/before the “character" where the cursor is.

I see and it seems quite easy to implements. I can make something. Just a question about `UnconditionalPaste`: when you copy multiple lines and use `UnconditionalPasteCharAfter`, how does it works ? Does it join lines ?

I think I should explain how special Put works in the README.md as anybody can write his own put function :D (I find this quite elegant and easy)

**Comment by thecontinium** [comment]
`UnconditionalPaste` joins the lines when multiple lines are copied and paste `charwise`; no newlines.

If you add to the README.md and I'll give it a go. 
If we can make the Special Put call the UnconditionalPaste functions this would be really flexible ?

**Comment by gbprod** [comment]
I'm working on it 😉

**Comment by gbprod** [comment]
I've made something [in this pull request](https://github.com/gbprod/yanky.nvim/pull/68), if you want to try it before I merge.

To have the same behavior than UnconditionalPaste, I think you should add :

```vim
nmap Pc <Plug>YankyPutBeforeCharwiseJoined
nmap pc <Plug>YankyPutAfterCharwiseJoined
nmap Pl <Plug>YankyPutBeforeLinewiseJoined
nmap pl <Plug>YankyPutAfterLinewiseJoined
```

I've also implemented `Blockwise` option ;)

Can you tell me if something is missing ?

**Comment by thecontinium** [comment]
Thanks. 

These function (when including the brackets) and cycles through ring correctly.

``` vim
nmap Pc (<Plug>YankyPutBeforeCharwiseJoined)
nmap pc (<Plug>YankyPutAfterCharwiseJoined)
nmap Pl (<Plug>YankyPutBeforeLinewiseJoined)
nmap pl (<Plug>YankyPutAfterLinewiseJoined)
```
If there was a configurable generic way to add any special Put to the ui and telescope pickers that would be great.

Is it possible to add these as actions in Telescope [pickers](https://github.com/gbprod/yanky.nvim#pickertelescopemappings) ?


Cheers

**Comment by gbprod** [comment]
hmm, that's a great idea.
I merge this #68 and I'll work on this

**Comment by thecontinium** [comment]
Let me know when you are ready and I can give it a test run.

**Comment by bagohart** [comment]
I just learned about this feature through the "news/breaking changes issue", thanks for implementing this!
So far, I have usually solved this by using `yil` for yanking a line with the inner line text object, and then modifying the paste is not necessary, but this way to do it is nice, too.
I'm not a fan of extending `p` to `pc` and `pl`, so I came up with `cp` as a mnemonic for "character-wise paste", which seems to be generally available.

**Comment by thecontinium** [comment]
Yes I agree extending `p` to `pl`, `pc` are not great mappings.

**Comment by thecontinium** [comment]
@gbprod you are missing the `Charwise` optional `modifier` in the [readme](https://github.com/gbprod/yanky.nvim#%EF%B8%8F-mappings-3)

**Comment by gbprod** [comment]
@thecontinium made something [here](https://github.com/gbprod/yanky.nvim/pull/70) if you want to try ;)
