### ISSUE TITLE
`YankyGPutBefore` and `YankyGPutAfter` swapped?

### ISSUE THREAD

**Issue by simonmandlik** [gbprod/yanky.nvim#71]
I found out that to achieve the same behavior as in native nvim, I have to set up like this

```lua
local map = vim.keymap.set
map({"n", "x"}, "p", "<Plug>(YankyPutAfter)")
map({"n", "x"}, "P", "<Plug>(YankyPutBefore)")
map({"n", "x"}, "gp", "<Plug>(YankyGPutBefore)")
map({"n", "x"}, "gP", "<Plug>(YankyGPutAfter)")
```

effectively switching the meanings of `gp` and `gP`. Then pasting works like in `nvim -u NONE`.

Is this a bug or feature?

**Comment by gbprod** [comment]
It was a bug, it has been fixed [here](https://github.com/gbprod/yanky.nvim/pull/69). 
I think you should update.
