### ISSUE TITLE
`YankyGPutIndent*`

### ISSUE THREAD

**Issue by simonmandlik** [gbprod/yanky.nvim#72]
Would it be possible to also add actions like `YankyGPutIndentAfter` and `YankyGPutIndentBefore`?

**Comment by gbprod** [comment]
I think you can achieve it using `<Plug>YankyGPutIndentAfter`]`.

**Comment by gbprod** [comment]
Let me know if it works for you

**Comment by simonmandlik** [comment]
Unfortunately it doesn't, it seems that the `]` mark is not created properly and gets me to the end of file

**Comment by gbprod** [comment]
Works for me like that : 

```lua
vim.keymap.set({ "n", "x" }, ")p", "<Plug>(YankyPutIndentAfter)`]", {})
```

**Comment by simonmandlik** [comment]
Thanks!
