### ISSUE TITLE
Confused by `Filter` behavior

### ISSUE THREAD

**Issue by simonmandlik** [gbprod/yanky.nvim#74]
Hi, I would like to setup `yanky.nvim` as follows:

```lua
local map = vim.keymap.set

map({"n", "x"}, "y", "<Plug>(YankyYank)")

map({"n", "x"}, "P", "<Plug>(YankyPutBefore)")
map({"n", "x"}, "gP", "<Plug>(YankyGPutBefore)")
map({"n", "x"}, "=P", "<Plug>(YankyPutBeforeFilter)")
map({"n", "x"}, "=gP", "<Plug>(YankyGPutBeforeFilter)")

map({"n", "x"}, "p", "<Plug>(YankyPutAfter)")
map({"n", "x"}, "gp", "<Plug>(YankyGPutAfter)")
map({"n", "x"}, "=p", "<Plug>(YankyPutAfterFilter)")
map({"n", "x"}, "=gp", "<Plug>(YankyGPutAfterFilter)")

map("n", "<A-n>", "<Plug>(YankyCycleForward)")
map("n", "<A-p>", "<Plug>(YankyCycleBackward)")
```

That is, standard `p`, `P` and `gP` work as usual, the `=` versions should also indent when pasted and are intended to be used linewise only and for programming.

With this code

```cpp
void test() {
    int a = 1;
    int b = 2;
    for (int i = 0; i < 10; ++i) {
        cout << a;
        cout << b;
    }
}
```

copying the two `cout` lines linewise, positioning the cursor on the line with `for`, I get

for `P`:
```cpp
void test() {
    int a = 1;
    int b = 2;
        cout << a;
        cout << b;
    for (int i = 0; i < 10; ++i) {
        cout << a;
        cout << b;
    }
}
```

with cursor on first `cout`

for `gP`:
```cpp
void test() {
    int a = 1;
    int b = 2;
        cout << a;
        cout << b;
    for (int i = 0; i < 10; ++i) {
        cout << a;
        cout << b;
    }
}
```

with cursor before at the beginning of the `for` line.

for `=P`
```cpp
void test() {
    int a = 1;
    int b = 2;
    cout << a;
    cout << b;
    for (int i = 0; i < 10; ++i) {
        cout << a;
        cout << b;
    }
}
```

with cursor on the first `cout`.

I would expect `=gP` to give me a combination of `gP` and `=P`, but I get this:

```cpp
void test() {
    int a = 1;
    int b = 2;
        cout << a;
    cout << b;
    for (int i = 0; i < 10; ++i) {
        cout << a;
        cout << b;
    }
}
```

which is neither indented correctly, and the cursor is on the `cout << b;` line, instead of on the `for` line as in the `gP` case.

The same behavior occurs for `p`. When I copy the two `int` definition lines, position the cursor on the `for` line, and perform `=gp`, I get

```cpp
void test() {
    int a = 1;
    int b = 2;
    for (int i = 0; i < 10; ++i) {
    int a = 1;
        int b = 2;
        cout << a;
        cout << b;
    }
}

```

with cursor on the pasted `int b = 2;` instead of one more line below.

I'm using the treesitter indentation, but I tested all wrongly indented examples and `=ip` indents everything correctly, so `=` should work properly.

Thank you!

**Comment by gbprod** [comment]
Thanks for your feedback!
I know there are some issues in special puts (especially with `gp`). 
I'll work to improve this in the next weeks :)

**Comment by gbprod** [comment]
I think cursor position issue should be fixed by #77 
Do you want to try before I merge ?

**Comment by simonmandlik** [comment]
Thanks. I tried switching and if the vanilla nvim behavior is the goal, it is unfortunately not fixed

This is what I get with `gP` in the same example as above now

<img width="308" alt="image" src="https://user-images.githubusercontent.com/16707112/209170378-11eec537-1dac-45e3-8e95-a0bed5c61012.png">

and this is what I get with `nvim -u NONE`

<img width="279" alt="image" src="https://user-images.githubusercontent.com/16707112/209170497-c9f03a82-db7d-4e2c-8c81-db6cc8b06c65.png">

and it's the same with `p`

**Comment by gbprod** [comment]
Hi!

I've updated the pull request, I think it should be ok, can you try again ?

Thanks !!!

**Comment by simonmandlik** [comment]
Hi again,

`p`, `P`, `gp`, `gP`, `=p` and `=P` all work fine, but `YankyGPutBeforeFilter` and `YankyGPutAfterFilter` still seem broken

This is what I get with `=gP`:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/16707112/210250635-cb79c6cf-844d-4b15-99b9-ed75fd9438a0.png">

**Comment by gbprod** [comment]
Oh! I thing I got it !
I'll update soon. Thanks for your time !!!

**Comment by gbprod** [comment]
It should be better now @simonmandlik !
I've to write more tests but it seems really better now

**Comment by simonmandlik** [comment]
Now it looks fine, thanks you very much :)

**Comment by gbprod** [comment]
\o/ 
Thanks for your feedback, I will use it like this for some times before merging to see if everything is ok.
If you find some strange cases, please report it :)
