### ISSUE TITLE
Feature request: remember yank ring position on next paste

### ISSUE THREAD

**Issue by mawkler** [gbprod/yanky.nvim#76]
I generally find that when I use the yank ring and paste mutliple times in a row I usually want to paste from the same position in the yank ring. Therefore I would personally like if the yank ring remembered my position between pastes. For example, if I yank the word `foo`, then yank `bar`, then paste with `<Plug>(YankyPutAfter)` (`bar`) and then cycle with `<Plug>(YankyCycleForward)` (`foo`), the next time I paste I would like yanky to paste `foo` again (currently it would paste `bar`).

If anything new is added to the paste ring (i.e. if I yank something) yanky would reset the ring position to the latest yanked item. What do you think about this idea?

**Comment by gbprod** [comment]
I think we can introduce a new option that will avoid [the reset of history ring](https://github.com/gbprod/yanky.nvim/blob/main/lua/yanky.lua#L171) and we should add a reset [in the on_yank event](https://github.com/gbprod/yanky.nvim/blob/main/lua/yanky.lua#L229).

I can't work on this right now but, you can make a PR if you want. Otherwise, I'll try to make something later.

**Comment by gbprod** [comment]
Hey!

I think the experimental option `update_register_on_cycle` can answer to your needs. Can you try this and make me a feedback ?

Thanks @mawkler

**Comment by mawkler** [comment]
Hi @gbprod, and thanks for working on this feature! I tried the steps in my original comment, but I still get the same behaviour. I used the following config on the latest commit (#cc3fc03):

Here's the config that I'm using

```lua
{
  'gbprod/yanky.nvim',
  keys = {
    { 'y',     '<Plug>(YankyYank)',          mode = {'n', 'x'} },
    { 'p',     '<Plug>(YankyPutAfter)',      mode = {'n', 'x'} },
    { 'P',     '<Plug>(YankyPutBefore)',     mode = {'n', 'x'} },
    { '<M-p>', '<Plug>(YankyCycleForward)',  mode = 'n' },
    { '<M-P>', '<Plug>(YankyCycleBackward)', mode = 'n' },
  },
  config = function()
    require('yanky').setup({
      highlight = { timer = 150 },
      update_register_on_cycle = true,
    })
  end
}
```

**Comment by gbprod** [comment]
Sorry, it should be configured like that : 

```lua
{
  'gbprod/yanky.nvim',
  keys = {
    { 'y',     '<Plug>(YankyYank)',          mode = {'n', 'x'} },
    { 'p',     '<Plug>(YankyPutAfter)',      mode = {'n', 'x'} },
    { 'P',     '<Plug>(YankyPutBefore)',     mode = {'n', 'x'} },
    { '<M-p>', '<Plug>(YankyCycleForward)',  mode = 'n' },
    { '<M-P>', '<Plug>(YankyCycleBackward)', mode = 'n' },
  },
  config = function()
    require('yanky').setup({
      highlight = { timer = 150 },
      { ring = { update_register_on_cycle = true },
    })
  end
}

**Comment by mawkler** [comment]
@gbprod That works perfectly! Thank you very much!
