### ISSUE TITLE
Does not work correctly with Expression register "=

### ISSUE THREAD

**Issue by ray-x** [gbprod/yanky.nvim#78]
Suppose I need to insert time into text, I can do  (`<c-M>` means ctrl-M)
`"=strftime('%c')<C-M>p`
In normal mode
With yanky.nvim default mapping of `p` , it does not insert `"=` register to current text. I have to `nunmap p` and `"=strftime('%c')<C-M>p` it will work.

**Comment by gbprod** [comment]
oh, interesting use case !
I see what's going on, I don't know for the moment how to fix it but I'll work on this soon

**Comment by gbprod** [comment]
Hey @ray-x !
This issue was quite hard to fix :sweat_smile: 
Can you try with #81 ? 
Thanks for your feedback!

**Comment by ray-x** [comment]
the branch works great, thanks!

**Comment by gbprod** [comment]
Thanks !!!
