### ISSUE TITLE
Don't include plenery.nvim as a git submodule

### ISSUE THREAD

**Issue by opalmay** [gbprod/yanky.nvim#82]
Hi, 
I've noticed this plugin as well as the other two of yours that I'm using (stay-in-place.nvim, substitue.nvim) have plenery.nvim as a git submodule. The plugin folders are 13MiB each on my computer.
It would be much better to handle it as other plugins do - to instead specify plenery.nvim as a dependency in the README and in the suggested plugin spec.

**Comment by gbprod** [comment]
Hey, thanks for your  feedback.
I was not aware that git submodules are downloaded... I only use nvim-lua/plenary.nvim for tests, I will try to fix it soon.

**Comment by gbprod** [comment]
Fixed!
Thanks
