### ISSUE TITLE
Yanky clipboard error

### ISSUE THREAD

**Issue by dat-le-4** [gbprod/yanky.nvim#91]
I got this error when open nvim on my mac.
![](https://user-images.githubusercontent.com/96510793/220671760-f29029e3-fd28-4561-bc5f-d0419b0cc095.png)
how can i fix this?

**Comment by gbprod** [comment]
Can you share your setup ?
Do you have something in `vim.g.clipboard` ?

**Comment by dat-le-4** [comment]
here is the link to my config git repo. https://github.com/dat-le-4/.config

**Comment by gbprod** [comment]
Seems that you have a problem with your vim clipboard manager, what's your result for `:checkhealth provider` ?

**Comment by dat-le-4** [comment]
I think I do have xsel installed. This is the message for clipboard when I ran :checkhealth. 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/96510793/221578337-a47c765d-c400-4993-b10b-58c652f87dc4.png">

**Comment by gbprod** [comment]
Can you try removing this from your config ? 
https://github.com/dat-le-4/.config/blob/master/nvim/lua/user/options.lua#L63-L76

If it does not works, can you try to run `xsel` from your terminal ?

**Comment by gbprod** [comment]
Regarding to your `.config` I think that the problem is that you're using a linux based config on MacOS. I don't know really MacOS but I'm not sure that xsel is available on it, so it seems weird to find it in your neovim config.

**Comment by dat-le-4** [comment]
I think the problem is I don't have xcel on my mac and I installed it brew install xsel. But now there is a new problem when I ran nvim.
![](https://user-images.githubusercontent.com/96510793/221873166-b840bdf8-c39e-4e01-aa6b-09f8abbea4b5.png)

**Comment by gbprod** [comment]
I really think that's not a problem related to Yanky. `xsel` is not mandatory for yanky, you can use your default clipboard manager.

However, I think you should unistall `xsel` and remove [vim.g.clipboard](https://github.com/dat-le-4/.config/blob/master/nvim/lua/user/options.lua#L63-L76) initialisation from your config.

**Comment by dat-le-4** [comment]
I think that will fix the problem. Thank you a lot!
