### ISSUE TITLE
[BUG] When open telescope and type too fast if throws an error

### ISSUE THREAD

**Issue by otavioschwanck** [gbprod/yanky.nvim#96]
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...ar/neovim/0.8.3/share/nvim/runtime/lua/vim/highlight.lua:65: in function 'range'
        ...local/share/nvim/lazy/yanky.nvim/lua/yanky/highlight.lua:45: in function 'highlight_put'
        ...s/otavio/.local/share/nvim/lazy/yanky.nvim/lua/yanky.lua:83: in function 'callback'
        ...s/otavio/.local/share/nvim/lazy/yanky.nvim/lua/yanky.lua:156: in function 'init_ring'
        ...s/otavio/.local/share/nvim/lazy/yanky.nvim/lua/yanky.lua:105: in function 'put'

**Comment by gbprod** [comment]
Hey!
Sorry for the late answer, can you provide your yanky setup ?
Are you using SQLite storage?

Do you have an error while typing in telescope or when you paste ?
Can you being more special about what you type ?

**Comment by otavioschwanck** [comment]
the problem is with my config, sorry about that!
